/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.easydynamics.java-conventions")
    java
    id("org.springframework.boot") version "2.5.0"
}

dependencies {
    api(project(":oscal-object-service"))
    api("org.springframework.boot:spring-boot-starter-data-rest:3.0.2")
    testImplementation(project(":oscal-data-repository-commons-tests"))
    testImplementation("org.springframework.boot:spring-boot-starter-test:3.0.2")
}

description = "oscal-rest-service-app"
