/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "oscal-rest-service-parent"
include(":oscal-data-repository-commons")
include(":oscal-data-repository-file")
include(":oscal-rest-service-app")
include(":oscal-data-repository-commons-tests")
include(":oscal-object-service")
