/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.easydynamics.java-conventions")
}

description = "oscal-data-repository-commons-tests"
