/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.easydynamics.java-conventions")
}

dependencies {
    api(project(":oscal-data-repository-file"))
    api("commons-beanutils:commons-beanutils:1.9.4")
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.2")
    testImplementation("org.springframework:spring-test:6.0.6")
}

description = "oscal-object-service"
