/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.easydynamics.java-conventions")
}

dependencies {
    api("gov.nist.secauto.oscal:liboscal-java:1.0.4.4")
    api("org.springframework:spring-core:6.0.6")
}

description = "oscal-data-repository-commons"
