/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.easydynamics.java-conventions")
}

dependencies {
    api(project(":oscal-data-repository-commons"))
    api("org.json:json:20230227")
    api("org.springframework.boot:spring-boot-starter-data-jpa:3.0.2")
    testImplementation(project(":oscal-data-repository-commons-tests"))
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.2")
    testImplementation("org.springframework:spring-test:6.0.6")
}

description = "oscal-data-repository-file"
