name: Publish package to GitHub Packages
on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Delete previous oscal-rest-service version
        uses: actions/delete-package-versions@v3.0.1
        with:
          package-name: com.easydynamics.oscal-rest-service-app
          package-type: maven
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Delete cached demo content and API
        run: |
          rm -rf ~/.m2/repository/.cache/download-maven-plugin/
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
