name: Run tests
on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    strategy:
      matrix:
        java: [11, 17]
    runs-on: ubuntu-latest
    name: "Build and test on Java ${{ matrix.java }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: "${{ matrix.java }}"
          distribution: 'temurin'
          cache: 'maven'
      - name: Build and test
        run: mvn package
